services:
  attacker:
    container_name: attacker
    build:
      context: .
      dockerfile: ./Docker/malcolm.dockerfile
    networks:
      ft_malcolm:
        ipv4_address: 172.20.0.2
    mac_address: AA:BB:CC:DD:EE:02
    cap_add:
      - NET_RAW
      - NET_ADMIN
  
  target:
    container_name: target
    build:
      context: .
      dockerfile: ./Docker/target.dockerfile
    networks:
      ft_malcolm:
        ipv4_address: 172.20.0.3
    mac_address: AA:BB:CC:DD:EE:03
    cap_add:
      - NET_RAW
      - NET_ADMIN
    depends_on:
      - attacker

networks:
  ft_malcolm:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24